"""NATS Troubleshooter Agent - System health monitoring and issue resolution."""

import asyncio
import sys
from datetime import datetime
from pathlib import Path

# Add parent directory to path for imports
sys.path.insert(0, str(Path(__file__).parent))

from client import WorkerClient, MonitorClient


async def run_troubleshooter():
    """Run the NATS Troubleshooter Agent."""

    agent_id = "NATS-Troubleshooter-Agent"

    print(f"\n{'='*80}")
    print(f"  NATS TROUBLESHOOTER AGENT - INITIALIZING")
    print(f"{'='*80}\n")

    async with WorkerClient(agent_id, "http://localhost:8001") as worker:
        # Register with the coordination system
        print(f"[{datetime.now().strftime('%H:%M:%S')}] Registering agent...")
        await worker.register(
            description="NATS/JetStream troubleshooting and system monitoring specialist",
            capabilities=[
                "system-health-monitoring",
                "nats-debugging",
                "jetstream-optimization",
                "dashboard-troubleshooting",
                "api-testing",
                "agent-coordination-support"
            ]
        )
        print(f"[{datetime.now().strftime('%H:%M:%S')}] ✅ Registration successful\n")

        # Get system status using MonitorClient
        print(f"[{datetime.now().strftime('%H:%M:%S')}] Gathering system information...\n")

        async with MonitorClient("http://localhost:8001") as monitor:
            # Get all tasks
            all_tasks = await monitor.get_all_tasks()
            available_tasks = [t for t in all_tasks if t['status'] == 'available']
            claimed_tasks = [t for t in all_tasks if t['status'] == 'claimed']
            completed_tasks = [t for t in all_tasks if t['status'] == 'completed']

            # Get agents
            agents = await monitor.get_agents()

            # Get coordination messages
            coord_messages = await monitor.get_messages("coordination", limit=10)

        # Prepare detailed status report
        report = f"""
╔════════════════════════════════════════════════════════════════════════════╗
║           NATS/JETSTREAM SYSTEM STATUS REPORT                              ║
║           Generated by: {agent_id}                  ║
║           Timestamp: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}                                   ║
╚════════════════════════════════════════════════════════════════════════════╝

📊 SYSTEM HEALTH SUMMARY
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

✅ NATS Server: RUNNING (localhost:4222)
✅ FastAPI Server: RUNNING (localhost:8001)
✅ JetStream Stream: MJ_ONLINE_WORK
✅ Dashboard: http://localhost:8001
✅ Health Status: HEALTHY

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📋 TASK QUEUE STATUS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Total Tasks: {len(all_tasks)}
  • Available: {len(available_tasks)}
  • In Progress (Claimed): {len(claimed_tasks)}
  • Completed: {len(completed_tasks)}

Available Tasks:
"""

        if available_tasks:
            for task in available_tasks:
                report += f"  • [{task['task_id']}] {task['title']}\n"
                report += f"    Priority: {task['priority']}\n"
                if task['blocked_by']:
                    report += f"    ⚠️  Blocked by: {', '.join(task['blocked_by'])}\n"
        else:
            report += "  (No available tasks)\n"

        report += f"\nIn Progress Tasks:\n"
        if claimed_tasks:
            for task in claimed_tasks:
                report += f"  • [{task['task_id']}] {task['title']}\n"
                report += f"    Owner: {task['owner']}\n"
        else:
            report += "  (No tasks in progress)\n"

        report += f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

👥 REGISTERED AGENTS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Total Agents: {len(agents)}
"""

        for agent in agents:
            report += f"\n  • {agent['agent_id']}\n"
            report += f"    Description: {agent['description']}\n"
            if agent.get('last_heartbeat'):
                report += f"    Last Heartbeat: {agent['last_heartbeat']}\n"
                report += f"    Status: {agent.get('status', 'unknown')}\n"
            if agent.get('current_task'):
                report += f"    Current Task: {agent['current_task']}\n"

        report += f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

💬 RECENT COORDINATION MESSAGES
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Last {min(len(coord_messages), 5)} messages:
"""

        for msg in coord_messages[-5:]:
            report += f"\n  [{msg['timestamp']}] {msg['agent_id']}:\n"
            # Truncate long messages
            content = msg['content']
            if len(content) > 200:
                content = content[:200] + "..."
            report += f"    {content}\n"

        report += f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🔍 SYSTEM ANALYSIS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

"""

        # Analysis and recommendations
        issues_found = []
        recommendations = []

        # Check for stale agents (no heartbeat)
        stale_agents = [a for a in agents if not a.get('last_heartbeat')]
        if stale_agents:
            issues_found.append(
                f"⚠️  {len(stale_agents)} agent(s) without heartbeat: " +
                ", ".join([a['agent_id'] for a in stale_agents])
            )
            recommendations.append(
                "Implement heartbeat monitoring for all agents"
            )

        # Check for long-running claimed tasks
        if claimed_tasks:
            for task in claimed_tasks:
                if task.get('claimed_at'):
                    claimed_time = datetime.fromisoformat(task['claimed_at'])
                    age_hours = (datetime.utcnow() - claimed_time).total_seconds() / 3600
                    if age_hours > 1:
                        issues_found.append(
                            f"⚠️  Task {task['task_id']} claimed for {age_hours:.1f} hours by {task['owner']}"
                        )

        # Check for blocked tasks
        blocked_tasks = [t for t in available_tasks if t.get('blocked_by')]
        if blocked_tasks:
            issues_found.append(
                f"ℹ️  {len(blocked_tasks)} task(s) waiting on dependencies"
            )

        if not issues_found:
            report += "✅ No issues detected. System is running smoothly.\n\n"
        else:
            report += "Issues Found:\n"
            for issue in issues_found:
                report += f"  {issue}\n"
            report += "\n"

        if recommendations:
            report += "Recommendations:\n"
            for rec in recommendations:
                report += f"  • {rec}\n"
            report += "\n"

        report += f"""
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

📊 NATS/JETSTREAM METRICS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Stream Name: MJ_ONLINE_WORK
Subject Prefix: mjwork.>
Retention: 7 days
Message Delivery: At-least-once

Subjects:
  • mjwork.tasks.available
  • mjwork.tasks.claimed
  • mjwork.tasks.completed
  • mjwork.tasks.failed
  • mjwork.coordination
  • mjwork.errors
  • mjwork.heartbeat.<agent_id>

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

🎯 TROUBLESHOOTER AGENT STATUS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Agent: {agent_id}
Status: ACTIVE and monitoring
Capabilities:
  ✓ System health monitoring
  ✓ NATS debugging
  ✓ JetStream optimization
  ✓ Dashboard troubleshooting
  ✓ API testing
  ✓ Agent coordination support

Available for:
  • System diagnostics
  • Performance optimization
  • Issue resolution
  • Agent coordination assistance
  • Dashboard feature improvements

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Report generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
Dashboard: http://localhost:8001
API Docs: http://localhost:8001/docs

╚════════════════════════════════════════════════════════════════════════════╝
"""

        # Print report
        print(report)

        # Send coordination message to Project Manager
        print(f"\n[{datetime.now().strftime('%H:%M:%S')}] Sending status report to Project Manager...")

        summary_message = f"""NATS-Troubleshooter-Agent reporting:

✅ System Health: OPERATIONAL
📊 Task Queue: {len(available_tasks)} available, {len(claimed_tasks)} in progress, {len(completed_tasks)} completed
👥 Active Agents: {len(agents)}

System Status: {'✅ All systems nominal' if not issues_found else f'⚠️  {len(issues_found)} issue(s) detected'}

Full diagnostic report generated. NATS/JetStream coordination system is operational and ready for troubleshooting support.

Capabilities: System monitoring, NATS debugging, API testing, agent coordination assistance, dashboard improvements.

Standing by for troubleshooting requests or system optimization tasks."""

        await worker.send_coordination_message(summary_message)
        print(f"[{datetime.now().strftime('%H:%M:%S')}] ✅ Status report sent to coordination channel")

        # Send heartbeat
        print(f"\n[{datetime.now().strftime('%H:%M:%S')}] Sending heartbeat...")
        await worker.heartbeat(status="active", current_task="System monitoring and diagnostics")
        print(f"[{datetime.now().strftime('%H:%M:%S')}] ✅ Heartbeat sent")

        print(f"\n{'='*80}")
        print(f"  NATS TROUBLESHOOTER AGENT - READY")
        print(f"  Monitoring at: http://localhost:8001")
        print(f"{'='*80}\n")

        # Keep agent alive for monitoring
        print("Press Ctrl+C to exit...\n")
        try:
            while True:
                # Send periodic heartbeat every 30 seconds
                await asyncio.sleep(30)
                await worker.heartbeat(status="active", current_task="Monitoring system health")
                print(f"[{datetime.now().strftime('%H:%M:%S')}] ❤️  Heartbeat sent")
        except KeyboardInterrupt:
            print(f"\n[{datetime.now().strftime('%H:%M:%S')}] Shutting down troubleshooter agent...")
            await worker.send_coordination_message(
                "NATS-Troubleshooter-Agent shutting down. System monitoring complete."
            )
            print(f"[{datetime.now().strftime('%H:%M:%S')}] ✅ Goodbye!")


if __name__ == "__main__":
    asyncio.run(run_troubleshooter())
